import type { NextPage } from "next"
import Head from "next/head"
import { useRef } from "react"
import API from "lib/api"
import { ChangeEvent } from "react"
import { useState } from "react"
import { useContext } from "react"
import { UserContext } from "context/UserContext"
import { MapContext } from "context/MapContext"
import { SearchLocation } from "interfaces"

const Home: NextPage = () => {
  const { user } = useContext(UserContext)
  const { map } = useContext(MapContext)

  const [resultsData, setResultsData] = useState<SearchLocation>([])
  const timeoutRef = useRef<NodeJS.Timeout>()
  const messageRef = useRef<any>(null)

  const debounce = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
    }
    timeoutRef.current = setTimeout(async () => {
      const { data } = await API.get(`/${messageRef.current.value}.json`, {
        params: {
          proximity: `${user.lat},${user.lng}`,
        },
      })

      const dataResult = data.features.map(
        ({ center, place_name, text }: any) => {
          return {
            coords: center,
            placeName: place_name,
            type: text,
          }
        }
      )

      setResultsData(dataResult)
      messageRef.current.value = ""
    }, 500)
  }

  const flyTo = (lng: number, lat: number) => {
    map?.flyTo({
      center: [lng, lat],
      zoom: 9,
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="menu-container">
        <input
          ref={messageRef}
          onChange={debounce}
          placeholder="Search location"
        />
        <div className="menu-dropdown">
          {resultsData
            ? resultsData.map(({ coords, placeName, type }, i) => (
                <div
                  onClick={() => flyTo(coords[0], coords[1])}
                  className="menu-dropdown-body"
                  key={i}
                >
                  <h1>{placeName}</h1>
                  <p>{type}</p>
                  <button className="menu-dropdown-button">Go</button>
                </div>
              ))
            : null}
        </div>
      </div>
    </>
  )
}

export default Home
